<hr>
Este material ha sido construido en conjunto con material suministrado por los profesores Pedro Atencio (Instituto Tecnológico Metropolitano), Carlos Mera (Universidad de Medellin), Albeiro Espinosa y Diego Patiño (Universidad Nacional de Colombia, Sede Medellín); a ellos les damos crédito.
<hr>

#  <center> VISIÓN ARTIFICIAL </center>
## Agenda del día
### Generalidades del curso
<ul>
  <li>Objetivos</li>
  <li>Contenido</li>
  <li>Metodología</li>
  <li>Evaluación</li>
</ul>

### Unidad 1 - Introducción
<ul>
  <li>Visión artificial</li>
  <li>**Paquetes científicos de Python (para la clase)**</li>
</ul>


# Unidad 1 - Introducción
<hr>

## 2. Paquetes científicos de Python
<br>

## Python
<br><br>
Python es un popular lenguaje de alto nivel. Puede manejar varias tareas como computación numérica, desarrollo web, programación de bases de datos, programación de redes de comunicación, procesamiento paralelo, etc.
<ul>
    <li>Es gratis.</li>
    <li>Está disponible en todos los sistemas operativos populares como Windows, Mac o Linux.</li>
    <li>Es un lenguaje interpretado. No hay necesidad de compilar o enlazar (linking).</li>
    <li>Brinda la capacidad de desarrollar rápido.</li>
    <li>Es sintacticamente más simple que C/C++/Fortran. Fácil de leer y entender.</li>
    <li>Tiene mucho soporte desde distintas comunidades: académica, científica, empresarial, etc. Por lo que se dispone de muchos paquetes para tareas específicas.</li>
    <li>Muchas universidades ya reemplazan MATLAB por Python.</li>
    <li>Los autores de investigación en ciencias computacionales adoptan Python como estandar para compartir sus códigos.</li>
    <li>Tipado dinámico.</li>
    <li>Python es para puristas: La indentación NO ES OPCIONAL, lo cual hace más fácil la lectura y documentación del código.</li>
</ul>
<hr>

## Ambientes de Python (Python Environments).
<br><br>
Un ambiente de Python es un gestor de paquetes y software utilitario, elaborado por la comunidad para desarrollar software de un tema especifico. Entre los ambientes mas populares de Python para computacion cientifica se encuentran:
<ul>
    <li><a href='https://python-xy.github.io'>PythonXY</a></li>
    <li><a href='https://www.continuum.io/why-anaconda'>Anaconda</a></li>
</ul>
<br>
Utilizar ambientes de Python permite olvidarse en gran parte de la instalacion de los paquetes necesarios para desarrollar un software especializado, asi como de evitar que se altere el Python del sistema operativo, lo cual podria tener consecuencias desastrosas.
<br><br>
Ambos ambientes son gratis y cuentan con gran soporte. En esta clase se hara uso de Anaconda, sin embargo sientase libre de elegir el paquete que mas le convenga.
<hr>

## Editor
<br>
Anaconda Python viene con un potente y util editor web llamada <b>Jupyter Notebook</b>, el cual hace las veces de un bloc de notas del cientifico, en el cual se puede trabajar contenido HTML para plasmar notas o ejercicios de experimentacion, asi como codigo Python. Esto presenta la gran ventaja de que se pueden ir generando resultados visuales a medida que se avanza en la experimentacion. Esto resulta muy util a la hora de escribir un articulo cientifico, por ejemplo...o para un profesor para recibir trabajos de sus estudiantes.
<br>
<center><i>Figura. Esta clase esta siendo presentada en Jupyter Notebook.</i></center>
<img src="res/m1_3/gui.jpg" alt="guinio" style="height:200px"></img>
<br>
Jupyter notebook no es exclusivo de Ananconda, es decir, se puede realizar una instalacion de este modulo por aparte.
<hr>

<hr>
## Ambientes virtuales (virtual environments)
<br>
Se conococen como ambientes virtuales, un "espacio" privado, en el cual se pueden realizar instalaciones de paquetes independiente del motor principal de Python. Dicho de otra forma, si usted quiere realizar tres proyectos de desarrollo y cada uno utiliza una version particular del paquete TensorFlow, entonces es conveniente crear un ambiente virtual para cada proyecto y gestionar los paquetes de forma individual, todos corriendo bajo el mismo motor de Python.
<br>
<b>virtualenv</b> es el paquete mas conocido para manejar este tipo de ambientes. Sin embargo, anaconda tiene su propio gestor de paquetes virtuales, el cual utilizaremos para esta clase.
<br>
<center><i>Figura. Ejemplo de la creacion en consola de un ambiente virtual utilizando <b>conda create</b>.</i></center>
<img src="res/m1_3/conda_create.png" alt="guinio" style="height:500px"></img>
<br>
La activacion de un ambiente virtual, se realiza mediante el comando: <b>source activate nombre_ambiente</b>.
<br>
<center><i>Figura. Ejemplo de la activacion en consola de un ambiente virtual utilizando <b>source activate</b>.</i></center>
<img src="res/m1_3/source_activate.png" alt="guinio" style="width:700px"></img>
<hr>

## Instalacion de paquetes o modulos de Python
<br>
Una vez tengamos configurado y activado nuestro ambiente virtual, podemos instalar los paquetes de python mediante la herramiento <a href='https://en.wikipedia.org/wiki/Pip_(package_manager)'>pip</a>, un sistema de administracion de paquetes muy popular.
<br>
La utilizacion de pip para instalar un paquete es: <b>pip install paquete</b>
<br>
Por ejemplo, para instalar el paquete numpy tendriamos el comando: <b> pip install numpy</b>. Para mayor informacion, consultar la <a href='https://pip.pypa.io/en/stable/'>documentacion oficial</a>.
<br><br>
Procedamos entonces a la instalacion de los paquetes necesarios para la clase (si falta otro podemos instalarlo luego):
<ul>
    <li><b><a href='https://www.scipy.org'>OpenCV</a></b>: librería para procesamiento de imágenes.</li>
    <li><b><a href='https://www.scipy.org'>scipy</a></b>: paquetes cientificos y numericos.</li>
    <li><b><a href='http://matplotlib.org'>matplotlib</a></b>: modulo de graficos cientificos.</li>
    <li><b><a href='http://scikit-image.org'>scikit-image</a></b>: modulo de procesamiento de imágenes y visión por computador, análogo a OpenCV.</li>
    <li><b><a href='http://pandas.pydata.org'>pandas</a></b>: modulo de analisis de datos.</li>
    <li><b><a href='http://jupyter.org'>Jupyter</a></b>: Jupyter Notebook.</li>
</ul>
<hr>

## Jupyter Notebook
<br>
Toda la clase estara orientada a trabajar en Jupyter Notebook, tanto para la presentacion de material teorico-practico, como para la entrega de trabajos.
<br>
Primero debemos inicializar Jupyter Notebook mediante los siguientes pasos:
<br>
### 1. Activacion del ambiente virtual
Para ello recuerde ya debio haber seguido los pasos anteriores de: creacion del ambiente virtual, activacion e instalacion de paquetes o modulos de python. Posteriormente puede activar el ambiente mediante: 
<br><br>
<font size="2" color="red">source activate</font> mi_ambiente
<br>
<h3>2. Ejecucion de Jupyter Notebook</h3>
<br>
Para ello se debe ejecutar el comando:
<br><br>
<font size='2' color='red'>jupyter notebook</font>
<br><br>
<b>Nota:</b> El notebook se abrira en la carpeta en la que este ubicado en la consola al momento de ejecutar el comando. Valide que esta en la carpeta correcta antes de ejecutar el comando.
<br>
<center><i>Figura. Comandos para la ejecucion de jupyter notebook.</i></center>
<img src="res/m1_4/jupyter_notebook.png" alt="guinio" style="height:200px"></img>
<br><br>
<center><i>Figura. Pantalla de bienvenida de jupyter notebook.</i></center>
<img src="res/m1_4/home.png" alt="guinio" style="height:300px"></img>
<br>

## Basicos de Python

In [1]:
#Esto en un comentario unico
'''
Esto es un
comentario
multiple
'''
#Existen multiples formas de importar paquetes o modulos de Python. A continuacion algunos ejemplos.

import numpy
a = numpy.zeros([1,3])
print(a)

[[0. 0. 0.]]


In [2]:
import numpy as np
b = np.zeros([1,4])
print(b)

from numpy import array
c = array([1,3,4,5])
print("c: ",c)

d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("d: ",d)

[[0. 0. 0. 0.]]
c:  [1 3 4 5]
d:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Python tiene tipado dinamico
a = 5
b = 1.4567
c = "hola mundo"
d = ['h', 'o', 'l', 'a']

print(a * c)
print(type(b))

hola mundohola mundohola mundohola mundohola mundo
<class 'float'>


In [4]:
#Los loops en python son muy sencillo
rango = range(3)
print(rango)

#rango con intervalo
print(range(3,10))

#Note la indentacion en el FOR. Una tabulacion, indica que la linea siguiente se encuentra contenido dentro de la
#linea anterior.
for i in range(1, 10):
    if(i%2 == 0):
        print("par: ", i)
    else:
        print("impar: ", i)

#El while es similar a cualquier lenguaje de programacion
c = 1
while(c <= 10):
    print("iteracion: ", c)
    c += 1

range(0, 3)
range(3, 10)
impar:  1
par:  2
impar:  3
par:  4
impar:  5
par:  6
impar:  7
par:  8
impar:  9
iteracion:  1
iteracion:  2
iteracion:  3
iteracion:  4
iteracion:  5
iteracion:  6
iteracion:  7
iteracion:  8
iteracion:  9
iteracion:  10


In [5]:
#En python todas la variables son objetos, por lo que tienen metodos implementados

parrafo = "That is not dead which can eternal lie, and with strange aeons even death may die"
palabras = parrafo.split()
print("cuantas palabras tiene el parrafo: ", len(palabras))
print("las palabras son: ", palabras)
print("cuantas letras a contiene el parrafo: ", parrafo.count('a'))
print("cual es la segunda palabra del parrafo: ", palabras[2])

cuantas palabras tiene el parrafo:  16
las palabras son:  ['That', 'is', 'not', 'dead', 'which', 'can', 'eternal', 'lie,', 'and', 'with', 'strange', 'aeons', 'even', 'death', 'may', 'die']
cuantas letras a contiene el parrafo:  9
cual es la segunda palabra del parrafo:  not


In [1]:
#ESTRUCTURAS DE DATOS
##===================================
#Listas
##===================================
a = [1,3,2.8,"hola"]
print(a)
b = ["34", 54]
print(b)
print(a+b)
print((a+b)[3])
a.sort()
print("lista ordenada: ", a)
print(sorted(a))
#Podemos generar una lista a partir de otra lista. Estos se conoce como List Comprehensions
l = [1,5,3,4,7]
lista_squared = [x*x for x in l]
print(lista_squared)

##===================================
#Tuplas
##===================================
tupla = ((2,3), (2,2), (3,4,2))
print(tupla)
print(tupla[0])

##===================================
#Set (conjuntos)
##===================================
lista = [1,2,3,4,1,1,3,3,10,11,24,24]
c1 = set(lista)
print(c1)
#Los conjuntos permiten operaciones de conjuntos (interseccion, union, etc.)
lista2 = [1,2,3,4,4,4,4,15,16,17,89]
c2 = set(lista2)

print(c1.intersection(c2))

##===================================
#Diccionarios: par llave-valor
##===================================
d = {'perro':'canino', 'lobo':'canino', 'gato':'felino', 'leon':'felino'}
print(d.keys())
print(d.values())
print(d['lobo'])

[1, 3, 2.8, 'hola']
['34', 54]
[1, 3, 2.8, 'hola', '34', 54]
hola
('lista ordenada: ', [1, 2.8, 3, 'hola'])
[1, 2.8, 3, 'hola']
[1, 25, 9, 16, 49]
((2, 3), (2, 2), (3, 4, 2))
(2, 3)
set([1, 2, 3, 4, 10, 11, 24])
set([1, 2, 3, 4])
['lobo', 'gato', 'perro', 'leon']
['canino', 'felino', 'canino', 'felino']
canino


In [ ]:
##Funciones
def mi_funcion(a,b,c):
    return a*b+c

print(mi_funcion(1,2,3))

### Conclusiones

<ul>
<li>Los paquetes especiales que utilizaremos para el tratamiento de imágenes, los abordaremos mediante avancemos con temas posteriores.</li>
<br>
<li>Hemos visto como se configura el espacio de trabajo para la clase, que se compone de un ambiente de Python, un ambiente virtual, una serie de paquetes o modulos y un editor que en nuestro caso es Jupyter Notebook.</li>
<li>Hemos abordado los conceptos básicos de Python, los cuales pueden reforzar mediante busqueda de informacion en internet o en libros al respecto... ¡Estamos listos!</li>
</ul>